spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hrm?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath:/com/gec/amolpsw/mapper/*.xml
  global-config:
    db-config:
      id-type: auto