server:
  port: 8802
spring:
  application:
    name: 'department-microservice'
  datasource:
    url: jdbc:mysql://localhost:3306/hrm?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root