eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8899
spring:
  application:
    name: service-zuul

zuul:
  routes:
    api-user-ms:
      path: /user/**
      url: http://localhost:8801/
      serviceId: userApi
    api-department-ms:
      path: /department/**
      url: http://localhost:8802/
      serviceId: departmentApi

