server:
  port: 8801
spring:
  application:
    name: 'user-microservice'
  datasource:
    url: jdbc:mysql://localhost:3306/hrm?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
config:
  jwt:
    # 加密密钥
    secret: Authorization
    # token有效时长
    expire: 3600
    # header 名称
    header: token


#mybatis-plus:
#  mapper-locations: classpath:/com/gec/amolpsw/mapper/*.xml
#  global-config:
#    db-config:
#      id-type: auto